### ISSUE TITLE
An important message

### ISSUE THREAD

**Issue by imborxcom** [PawelPleskaczynski/nasa-apod-node#2]
Hi Pawel,

I check all of your work and I'm impressed with your knowledge in different programming languages and all of them related with astronomy. I'm building an astronomy project and I'd like to contact you to see if it is actually posible to hire you for this project (if you are interested).

Can you give me your e-mail or skype id? Or if you want, you can write me to contacto@imborx.com

Cheers!

p.s. Sorry to write you in Issues section but I can't see any way to contact you.

**Comment by PawelPleskaczynski** [comment]
Hi, my email is pawelpleskaczynski@gmail.com, you can write to me!
